### ISSUE TITLE
Why shifting from reqwest to surf?

### ISSUE THREAD

**Issue by akashgurava** [iamsauravsharma/alpha_vantage#41]
Just went through commit history looks like you are shifting from reqwest to surf.

**Comment by iamsauravsharma** [comment]
Code was shifted from reqwest to surf temporarily to support async-std runtime used by my experimental personal project without burden to maintain two different branches for reqwest and surf. I am planning to support both reqwest and surf with the help of feature flag (reqwest/surf as default feature). I will readd reqwest support within one week or two-week time period before next release.

**Comment by iamsauravsharma** [comment]
Closing this issue since support for reqwest is readded as well as support for other custom clients. PR #42 added support for both reqwest and surf as well as an easy way for adding support for other custom HTTP clients such as isahc by implementing HttpClient trait for custom client struct.
