### ISSUE TITLE
Hard to hold the client as a struct field without specifying the lifetime everywhere

### ISSUE THREAD

**Issue by metlos** [iamsauravsharma/alpha_vantage#51]
First of all, thanks for a lovely crate!

The only problem I have is that the API client is defined with a lifetime of the supplied API key and therefore it is impossible to hold the instantiated client in a struct without having to specify the lifetime in that struct, too. This kinda explodes if one tries to incorporate your library into an existing code base.

It is also not possible to construct the API client anew for each request, without also constructing a whole new HTTP client (which would be a hacky way of working around the above problem). Having to create a new HTTP client and new ApiClient for each request kind of defeats the purpose of the https://github.com/iamsauravsharma/alpha_vantage/pull/49 that aimed to reduce the memory consumption :)

IMHO, owning the API key is not that much of a memory consumption issue but would greatly improve the usability of the library.

That said, I am not that well versed in Rust so maybe I'm just not seeing the way.

What I would like to do is this:

```rust
pub struct MyExistingStructWithoutLifeTime {
  ...
  alpha_vantage_client: alpha_vantage::ApiClient,
}
```

or this:
```rust
pub fn from_env() -> Result<alpha_vantage::ApiClient> {
  let api_key = env::var("API_KEY")?;
  Ok(alpha_vantage::ApiClient::set_api(api_key))
}
```

**Comment by iamsauravsharma** [comment]
#52 will fix issue
